// themes.js — shared theme definitions for all extension surfaces
// Loaded by content.js (via manifest), popup.html, and options.html

const BML_THEME_KEY = 'bml_theme';
const BML_DEFAULT_THEME = 'material';

const BML_THEMES = {
  midnight: {
    name: 'Midnight',
    colorScheme: 'dark',
    vars: {
      '--bml-panel':           '#0d0d1a',
      '--bml-page':            '#08080f',
      '--bml-sunken':          '#0a0a18',
      '--bml-surface':         '#12122a',
      '--bml-raised':          '#18183a',
      '--bml-input':           '#1a1a30',
      '--bml-hover':           '#222248',
      '--bml-active':          '#2e2e58',
      '--bml-tab-bg':          '#1a1a2e',
      '--bml-border':          '#32325a',
      '--bml-border-subtle':   '#262648',
      '--bml-border-strong':   '#3a3a68',
      '--bml-border-dim':      '#1e1e38',
      '--bml-heading':         '#eeeeff',
      '--bml-text':            '#d8d8f8',
      '--bml-text-2':          '#c8c8e8',
      '--bml-text-secondary':  '#aaaacc',
      '--bml-text-label':      '#9090b8',
      '--bml-text-muted':      '#7878a8',
      '--bml-text-dim':        '#6868a0',
      '--bml-text-faint':      '#5858a0',
      '--bml-text-ghost':      '#4a4a80',
      '--bml-accent':          '#8888ff',
      '--bml-accent-alt':      '#a855f7',
      '--bml-gradient-from':   '#5858cc',
      '--bml-gradient-to':     '#7c4dff',
      '--bml-success':         '#4ade80',
      '--bml-success-glow':    '#4ade8066',
      '--bml-success-text':    '#80e090',
      '--bml-success-bg':      '#2a5a2a',
      '--bml-error':           '#ff6b6b',
      '--bml-error-text':      '#ff8888',
      '--bml-error-bg':        '#5a2a2a',
      '--bml-stat-num':        '#7070c0',
      '--bml-type-path':       '#1a2e1a',
      '--bml-type-query':      '#1a1a2e',
      '--bml-type-script':     '#2e1a2e',
      '--bml-type-replace':    '#2e2e1a',
      '--bml-type-switchroot': '#1a2e2e',
      '--bml-danger-bg':       '#180a0a',
      '--bml-danger-border':   '#3a1818',
      '--bml-danger-text':     '#e09090',
      '--bml-danger-dim':      '#6a3a3a',
      '--bml-danger-btn-border':'#5a2020',
      '--bml-danger-btn-text': '#c06060',
    }
  },

  material: {
    name: 'Oceanic',
    colorScheme: 'dark',
    vars: {
      '--bml-panel':           '#263238',
      '--bml-page':            '#1e272c',
      '--bml-sunken':          '#222b30',
      '--bml-surface':         '#2e3c43',
      '--bml-raised':          '#37474f',
      '--bml-input':           '#2e3c43',
      '--bml-hover':           '#405860',
      '--bml-active':          '#4a6870',
      '--bml-tab-bg':          '#2e3c43',
      '--bml-border':          '#3e5660',
      '--bml-border-subtle':   '#344850',
      '--bml-border-strong':   '#506870',
      '--bml-border-dim':      '#2e4048',
      '--bml-heading':         '#eeffff',
      '--bml-text':            '#cce0e8',
      '--bml-text-2':          '#b8d0da',
      '--bml-text-secondary':  '#9ab8c4',
      '--bml-text-label':      '#9cb9c6',
      '--bml-text-muted':      '#8caab7',
      '--bml-text-dim':        '#7e9dab',
      '--bml-text-faint':      '#7898a6',
      '--bml-text-ghost':      '#6b8d9c',
      '--bml-accent':          '#80cbc4',
      '--bml-accent-alt':      '#89ddff',
      '--bml-gradient-from':   '#4db6ac',
      '--bml-gradient-to':     '#80cbc4',
      '--bml-success':         '#c3e88d',
      '--bml-success-glow':    '#c3e88d66',
      '--bml-success-text':    '#c3e88d',
      '--bml-success-bg':      '#2e4228',
      '--bml-error':           '#f07178',
      '--bml-error-text':      '#f48a90',
      '--bml-error-bg':        '#3e2828',
      '--bml-stat-num':        '#80cbc4',
      '--bml-type-path':       '#2a4032',
      '--bml-type-query':      '#283a44',
      '--bml-type-script':     '#3a2842',
      '--bml-type-replace':    '#3e3a28',
      '--bml-type-switchroot': '#284040',
      '--bml-danger-bg':       '#302020',
      '--bml-danger-border':   '#4a2828',
      '--bml-danger-text':     '#f48a90',
      '--bml-danger-dim':      '#6a4040',
      '--bml-danger-btn-border':'#7a4040',
      '--bml-danger-btn-text': '#f48a90',
    }
  },

  light: {
    name: 'Light',
    colorScheme: 'light',
    vars: {
      '--bml-panel':           '#ffffff',
      '--bml-page':            '#f0f1f4',
      '--bml-sunken':          '#f5f6f8',
      '--bml-surface':         '#f0f1f5',
      '--bml-raised':          '#e8e9ee',
      '--bml-input':           '#f0f1f4',
      '--bml-hover':           '#e0e1e8',
      '--bml-active':          '#d4d5de',
      '--bml-tab-bg':          '#e0e1e6',
      '--bml-border':          '#c8c9d2',
      '--bml-border-subtle':   '#d8d9e0',
      '--bml-border-strong':   '#b0b1bc',
      '--bml-border-dim':      '#dcdde4',
      '--bml-heading':         '#1a1a30',
      '--bml-text':            '#2a2a48',
      '--bml-text-2':          '#3a3a58',
      '--bml-text-secondary':  '#4a4a68',
      '--bml-text-label':      '#5a5a78',
      '--bml-text-muted':      '#6a6a88',
      '--bml-text-dim':        '#7a7a98',
      '--bml-text-faint':      '#8888a0',
      '--bml-text-ghost':      '#a0a0b4',
      '--bml-accent':          '#4848b8',
      '--bml-accent-alt':      '#7040e8',
      '--bml-gradient-from':   '#4848b8',
      '--bml-gradient-to':     '#7040e8',
      '--bml-success':         '#15803d',
      '--bml-success-glow':    '#16a34a44',
      '--bml-success-text':    '#15803d',
      '--bml-success-bg':      '#dcfce7',
      '--bml-error':           '#b91c1c',
      '--bml-error-text':      '#b91c1c',
      '--bml-error-bg':        '#fee2e2',
      '--bml-stat-num':        '#4848b8',
      '--bml-type-path':       '#e0f0e0',
      '--bml-type-query':      '#dceefa',
      '--bml-type-script':     '#f0e0f4',
      '--bml-type-replace':    '#faf4d8',
      '--bml-type-switchroot': '#daf0f0',
      '--bml-danger-bg':       '#fef2f2',
      '--bml-danger-border':   '#fca5a5',
      '--bml-danger-text':     '#b91c1c',
      '--bml-danger-dim':      '#dc2626',
      '--bml-danger-btn-border':'#f87171',
      '--bml-danger-btn-text': '#b91c1c',
    }
  }
};

// Apply theme CSS variables to a DOM element
function bmlApplyTheme(themeId, el) {
  const theme = BML_THEMES[themeId] || BML_THEMES[BML_DEFAULT_THEME];
  for (const [k, v] of Object.entries(theme.vars)) {
    el.style.setProperty(k, v);
  }
  if (el === document.documentElement || el === document.body) {
    document.documentElement.style.colorScheme = theme.colorScheme || 'dark';
  }
}
